In [3]:
import math
import numpy as np
import random as rand
def get_details_for_data():
    print("Enter number of hidden layers")
    hd_layer_num=int(input())
    print("Enter dimensions of x_data")
    x_dim=int(input())
    return hd_layer_num,x_dim

In [4]:
def get_hidden_layer_info(nohid):
    hid_data=[]
    for i in range(nohid):
        print("Enter no of neurons in hidden layer "+str(nohid+1))
        hid_data.append(int(input()))
    hid_data.append(1)
    return hid_data
        

In [5]:
def get_data(x):     #function to read data from file
    datafile=open(x,"r")
    datalist=[]
    for line in datafile:
        z=line.split(",")
        x=[float(i) for i in z]
        datalist.append(x)
    f=np.matrix(datalist)
    return f

In [6]:
def sigmoid(z):    #function to calculate sigmoid value
    temp=1/(1+math.e**(z*-1))
    return temp

In [7]:
def sig_dash(input):
    return sigmoid(input)*(1-sigmoid(input))

In [15]:
def initialize_weight_for_all_layers(dim_x,hidden):
    weights=[]
    temp_x_wt=[[[1]for i in range(dim_x)] for i in range(hidden[0])]
    weights.append(temp_x_wt)
    for i in range(0,len(hidden)-1):
        temp_wt=[]
        for j in range(0,hidden[i+1]):
            k_wt=[]
            for g in range(0,hidden[i]):
                k_wt.append([1])
            temp_wt.append(k_wt)
        weights.append(temp_wt)
    return weights
            
        

In [16]:
def feed_forward(hidden,weights,x):
    outputs=[]
    inputs=[]
    inputs.append(np.transpose(x).tolist())
    for i in range(0,len(weights)):
        weight_session=weights[i]
        fin=np.matrix(weights[i][0])
        for j in range(1,len(weight_session)):
            k=np.matrix(weight_session[j])
            fin=np.column_stack([fin,k])
        
        x=(np.matmul(np.transpose(fin),np.transpose(x)))
        inputs.append(x.tolist())
        
        
        
        x=np.transpose(x)
        x=x.tolist()
        lis=[]
        for f1 in x:
            mattem=[]
            for f2 in f1:
                mattem.append(sigmoid(f2))
            lis.append(mattem)
        x=np.matrix(lis)
        outputs.append(np.transpose(x).tolist())
        
    return x,outputs,inputs
        
    
    
    

In [17]:
def delta_for_out_layer(weights,y,d,inputs):
    deltalist=[]
    weights=weights[len(weights)-1]
    inputs=inputs[len(inputs)-1]
    error=y-d
    inputs=np.matrix(inputs)
    inputs=inputs.sum(axis=0)
    inputs=inputs.tolist()
    inputs=[[sig_dash(i[0])]for i in inputs]
    delta=np.dot(error,inputs)
    deltalist.append(delta.tolist())
    return deltalist

In [18]:
def delta_for_hidden(weights,outputs,inputs,delta):
    for i in range(len(weights)-2,-1,-1):
        prev_delta=delta[0]
        prev_wt=weights[i+1]
        fin1=np.matrix(prev_wt[0])
        for j in range(1,len(prev_wt)):
            k=np.matrix(prev_wt[j])
            fin1=np.column_stack([fin1,k])
        

        new_delta=np.matmul(fin1,prev_delta)
        inp=[[sig_dash(d)for d in k]for k in inputs[i+1]]
        inp=np.matrix(inp)
        inp=inp.tolist()
        #print(inp)
        new_delta=new_delta.tolist()
        #print(new_delta)
        #print("\n")
        new_delta=[[inp[j][0]*new_delta[j][0]]for j in range(0,len(inp))]
        delta.insert(0,new_delta)
    return delta

In [68]:
def recalc_weights(weights,weightsn1,delta,inputs,alpha,eta,outputs):
    weightsnp1=[]
    for i in range(0,len(weights)):
        weight_session=weights[i]
        fin=np.matrix(weights[i][0])
        for j in range(1,len(weight_session)):
            k=np.matrix(weight_session[j])
            fin=np.column_stack([fin,k])

        
        weight_sessionn1=weightsn1[i]
        finn1=np.matrix(weightsn1[i][0])
        for j in range(1,len(weight_sessionn1)):
            kn1=np.matrix(weight_sessionn1[j])
            finn1=np.column_stack([finn1,kn1])
        
        temp_yeta=eta*np.matrix(outputs[i])
        temp_yeta=temp_yeta.tolist()
        mylist=[]
        finnp1=fin+alpha*finn1
        finnp1=finnp1.transpose()
        print(finnp1)
        finnp1=finnp1.tolist()

        delt=delta[i+1]
        
        templist=[]
        for i in range(len(temp_yeta)):
            templist.append([temp_yeta[i][0]*delt[i][0]])

        rlist=[]
        for i in range(0,len(finnp1)):
            newlist=[]
            for j in range(0,len(finnp1[i])):
                newlist.append(finnp1[i][j]+templist[i][0])
            rlist.append(newlist)
        finnp1=np.matrix(finnp1)
        rlist=np.matrix(rlist)
        finnp1=finnp1+rlist
        print(finnp1)
        print(weights[i+1])
        print("\n\n")
    return weights
            
            
        

        
        
        

        
        
    

In [69]:
x=(get_data("x_data.txt"))
y=get_data("y_data.txt")
weights=(initialize_weight_for_all_layers(3,[2,2,1]))
for i in range(0,1):
    f,outputs,inputs=(feed_forward([2,2,1],weights,x[i]))
    f=f.tolist()
    z=f
    deltalist=delta_for_out_layer(weights,y[i],z,inputs)
    delta=delta_for_hidden(weights,outputs,inputs,deltalist)
    weights=recalc_weights(weights,weights,delta,inputs,0.1,0.1,outputs)
    print("\n\n\n")
    print("weights:" +str(weights))



[[ 1.1  1.1  1.1]
 [ 1.1  1.1  1.1]]
[[ 2.20022519  2.20022519  2.20022519]
 [ 2.20022519  2.20022519  2.20022519]]
[[[1], [1]]]



[[ 1.1  1.1]
 [ 1.1  1.1]]


IndexError: list index out of range